name: OCI Publication

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-oci-image:
    runs-on: desktop-linein-passthrough
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Publish OCI installer image
        env:
          OCI_IMAGE: ghcr.io/rosspeoples/linein-passthrough
          OCI_REGISTRY_USERNAME: ${{ secrets.PUBLISH_GITHUB_USERNAME }}
          OCI_REGISTRY_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
          OCI_VERSION_TAG: ${{ github.sha }}
          OCI_LATEST_TAG: latest
        run: bash scripts/publish-oci-image.sh
